### PR TITLE
Fix #16: Can't build with cmake and g++ 9.2.0

### LINKED ISSUE #16: Can't build with cmake and g++ 9.2.0
I try to build ECS with my other Project (didn't work), so I fork ESC and add my typical cmake-file and compiler-options (try out C++14 and C++17): https://github.com/abeimler/ECS

OS: Arch Linux x86_64 (4.16.81-1-MANJARO)
Compiler: c++ (GCC) 9.2.0
CMake: 3.15.5

**Build:**
```bash
mkdir build
cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DECS_SAMPLE_BUILD:BOOL="1"
cmake --build build
```

**Error:**
```bash
[ 50%] Building CXX object CMakeFiles/sample.dir/sample.cpp.o
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/ext/new_allocator.h:146:8: error: allocation of incomplete type 'ECS::Entity' [clang-diagnostic-error]
                            _Up(std::forward<_Args>(__args)...)))
                            ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/alloc_traits.h:483:24: note: in instantiation of exception specification for
 'construct<ECS::Entity, ECS::World *, unsigned long &>' requested here
        noexcept(noexcept(__a.construct(__p, std::forward<_Args>(__args)...)))
                              ^
ECS.h:454:4: note: in instantiation of exception specification for 'construct<ECS::Entity, ECS::World *, unsigned long &>
' requested here
                        std::allocator_traits<EntityAllocator>::construct(entAlloc, ent, this, lastEntityId);
                        ^
ECS.h:131:8: note: forward declaration of 'ECS::Entity'
        class Entity;
              ^
1 error generated.
Error while processing sample.cpp.
Found compiler errors, but -fix-errors was not specified.
Fixes have NOT been applied.

Found compiler error(s).
make[3]: *** [CMakeFiles/sample.dir/build.make:63: CMakeFiles/sample.dir/sample.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:105: CMakeFiles/sample.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/sample.dir/rule] Error 2
make: *** [Makefile:131: sample] Error 2
```

### PR DESCRIPTION
**Pull request by abeimler**
see #16 for the Error ... basically "error: allocation of incomplete type" you try to allocate (in World) an per-define class Entity.
Solution: Move Enity class definition before World.

I also add a CMakeLists.txt file.

### CODE REVIEW

**Comment by redxdev** [comment]
I'd prefer it if you kept this PR just to the change to `ECS.h`. I'd rather not introduce an additional build system just for a single header + sample file.

**Review by redxdev — CHANGES_REQUESTED** [review]
Only include the changes to ECS.h

**Review by redxdev — APPROVED** [review]
